# Change these first
owner: auto-mat # Your GitHub organization or username, where this repository lives
repo: automat-statuspage # The name of this repository

sites:
  - name: Automat hlavní stranka : auto-mat.cz
    url: https://auto-mat.cz
  - name: Automat eshop : obchod.auto-mat.cz
    url: https://obchod.auto-mat.cz/
  - name: Cyklisté sobě : www.cyklistesobe.cz
    url: https://www.cyklistesobe.cz/
  - name: Do Práce na Kole : dopracenakole.cz
    url: https://dopracenakole.cz
  - name: Do Práce na Kole - reg : dpnk.dopracenakole.cz
    url: https://dpnk.dopracenakole.cz
  - name: Do Práce na Kole - reg test : test.dopracenakole.cz
    url: https://test.dopracenakole.cz
  - name: Městem na Kole : mestemnakole.cz
    url: https://mestemnakole.cz
  - name: Mapa Městem na Kole : mapa.prahounakole.cz
    url: https://mapa.prahounakole.cz
  - name: Geoserver : geoserver1.prahounakole.cz
    url: https://geoserver1.prahounakole.cz
  - name: Dlaždice pro mapu
    url: https://tiles.prahounakole.cz/
  - name: Zažit Město Jinak : zazitmestojinak.cz
    url: https://zazitmestojinak.cz
  - name: Passbolt : automat.passbolt.klub-pratel.cz
    url: https://automat.passbolt.klub-pratel.cz
  - name: Klub Přatel - Automat : automat.klub-pratel.cz
    url: https://automat.klub-pratel.cz
  - name: Klub Přatel - Brontosaurus : brontosaurus.klub-pratel.cz
    url: https://brontosaurus.klub-pratel.cz
  - name: Klub Přatel - Investigace : investigace.klub-pratel.cz
    url: https://investigace.klub-pratel.cz
  - name: Klub Přatel - Test : test.klub-pratel.cz
    url: https://test.klub-pratel.cz
  - name: Limesurvey : limesurvey.dopracenakole.net
    url: https://limesurvey.dopracenakole.net
  - name: Dlaždice pro mapu


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /automat-statuspage
  logoUrl: https://github.com/auto-mat/automat-statuspage/raw/master/assets/automat_logo_01_logo.png
  name: Automat Statuspage - Upptime
  introTitle: "Automat z.s. Status webových služeb"
  introMessage: Souhrn dostupnosti webových služeb Automatu
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
