# Change these first
owner: auto-mat # Your GitHub organization or username, where this repository lives
repo: automat-statuspage # The name of this repository

sites:
  - name: Automat hlavní stranka
    url: https://auto-mat.cz
  - name: Automat eshop
    url: https://obchod.auto-mat.cz/
  - name: Cyklisté sobě
    url: https://www.cyklistesobe.cz/
  - name: Do Práce na Kole
    url: https://dopracenakole.cz
  - name: Do Práce na Kole - reg
    url: https://dpnk.dopracenakole.cz
  - name: Do Práce na Kole - reg test
    url: https://test.dopracenakole.cz
  - name: Městem na Kole
    url: https://mestemnakole.cz
  - name: Mapa Městem na Kole
    url: https://mapa.prahounakole.cz
  - name: Geoserver
    url: https://geoserver1.prahounakole.cz
  - name: Zažit Město Jinak
    url: https://zazitmestojinak.cz
  - name: Passbolt
    url: https://automat.passbolt.klub-pratel.cz
  - name: Klub Přatel - Automat
    url: https://automat.klub-pratel.cz
  - name: Klub Přatel - Brontosaurus
    url: https://brontosaurus.klub-pratel.cz
  - name: Klub Přatel - Investigace
    url: https://investigace.klub-pratel.cz
  - name: Klub Přatel - Test
    url: https://test.klub-pratel.cz
  - name: Limesurvey
    url: https://limesurvey.dopracenakole.net


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /automat-statuspage
  logoUrl: https://github.com/auto-mat/automat-statuspage/raw/master/assets/automat_logo_01_logo.png
  name: Automat Statuspage - Upptime
  introTitle: "Automat z.s. Status webových služeb"
  introMessage: Souhrn dostupnosti webových služeb Automatu
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
